### ISSUE TITLE
cpu version hfs

### ISSUE THREAD

**Issue by GuideWsp** [yun-liu/hfs#1]
will u provide the cpu version hfs on windows? i wish to test the hfs on win7, but your code need cuda, so do you have the cpu version? is it possible to open it? if possible, it will be very helpful. looking forward to your reply.

**Comment by yun-liu** [comment]
We have not prepared for a CPU version. Maybe you can create it by replacing the GPU-SLIC with CPU-SLIC and replacing Magnitude.cu with cpu code.

**Comment by GuideWsp** [comment]
thanks, our team will try it.

**Comment by Yujun-Shi** [comment]
Actually, now a cpu version of the code is also provided in our OpenCV_Contrib version. check out the following link for both the cpu/gpu version of the code: https://github.com/opencv/opencv_contrib/tree/master/modules/hfs
